# Generated by Django 3.2.7 on 2021-10-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_inventroy_product_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='prduct',
            new_name='product',
        ),
    ]
