# Generated by Django 4.0.3 on 2022-03-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='daily_rate',
            new_name='daily_rental_rate',
        ),
    ]
