# Generated by Django 4.0.3 on 2022-03-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_rename_daily_rate_film_daily_rental_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
