# Generated by Django 4.0.3 on 2022-03-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_film_is_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genre',
            new_name='genre_id',
        ),
    ]
