# Generated by Django 4.0.3 on 2022-03-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_rename_genre_film_genre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='release_year',
            new_name='published_date',
        ),
    ]
